
const deliveryData = [
    { district: 'Dhaka', area: 'Salimullah Road(Mohammadpur)' },
    { district: 'Dhaka', area: 'Dhanmondi - Road 3' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-1' },
    { district: 'Dhaka', area: 'Kallyanpur(Dhaka)' },
    { district: 'Dhaka', area: 'Shyamoli(Dhaka)' },
    { district: 'Dhaka', area: 'Adabor(Mohammadpur)' },
    { district: 'Dhaka', area: 'Darussalam (Technical-Kallayanpur)' },
    { district: 'Dhaka', area: 'Gabtoli (Dhaka)' },
    { district: 'Dhaka', area: 'Pallabi(Mirpur-12)' },
    { district: 'Dhaka', area: 'Lalmatia(Dhaka)' },
    { district: 'Dhaka', area: 'Mirpur DOHS(Mirpur-12)' },
    { district: 'Dhaka', area: 'Kochukhet(Mirpur 14)' },
    { district: 'Dhaka', area: 'Gudaraghat (Badda Link Road)' },
    { district: 'Dhaka', area: 'Agargaon(Dhaka)' },
    { district: 'Dhaka', area: 'Monipur(60-feet)' },
    { district: 'Dhaka', area: 'Sher-e-Bangla Agricultural University' },
    { district: 'Dhaka', area: 'Ibrahimpur(Mirpur 14)' },
    { district: 'Dhaka', area: 'Kakoli(Banani)' },
    { district: 'Dhaka', area: 'Balughat Bazar Road(Mirpur)' },
    { district: 'Dhaka', area: 'North Kafrul(Mirpur)' },
    { district: 'Dhaka', area: 'Vashantek(Mirpur)' },
    { district: 'Dhaka', area: 'Manikdi(Vasantek-Mirpur)' },
    { district: 'Dhaka', area: 'Matikata(Mirpur)' },
    { district: 'Dhaka', area: 'Bangladesh Army Headquerters(Dhaka Cantonment)' },
    { district: 'Dhaka', area: 'Rupnagar Residential(Mirpur 7)' },
    { district: 'Dhaka', area: 'Duaripara-Pallabi(Mirpur 12)' },
    { district: 'Dhaka', area: 'Dhaka Dental College(Mirpur 14)' },
    { district: 'Dhaka', area: 'Bagbari (Dhaka)' },
    { district: 'Dhaka', area: 'Mazar Road (Mirpur)' },
    { district: 'Dhaka', area: 'Shagufta(Mirpur)' },
    { district: 'Dhaka', area: 'Bawnia Bazar(Uttara)' },
    { district: 'Dhaka', area: 'Baigertek-ECB(Mirpur)' },
    { district: 'Dhaka', area: 'Madina nagar(Mirpur 11)' },
    { district: 'Dhaka', area: 'Chuti Ghor Road (Nikunjo-Khilkhet)' },
    { district: 'Dhaka', area: 'Mastertek-Manikdi(Mirpur)' },
    { district: 'Dhaka', area: 'Balughat(Mirpur)' },
    { district: 'Dhaka', area: 'Barontek-Balughat(Mirpur)' },
    { district: 'Dhaka', area: 'Golartek(Mirpur)' },
    { district: 'Dhaka', area: 'Uttar Para (Khilkhet)' },
    { district: 'Dhaka', area: 'Shewra (Kuril-Dhaka)' },
    { district: 'Dhaka', area: 'Ainusbag(Dakshinkhan)' },
    { district: 'Dhaka', area: 'Uttarkhan(Dhaka)' },
    { district: 'Dhaka', area: 'Dakshinkhan(Dhaka)' },
    { district: 'Dhaka', area: 'TIC Colony(Uttara Sector-6)' },
    { district: 'Dhaka', area: 'Askona(Dhaka)' },
    { district: 'Dhaka', area: 'Tolna (Khikhet)' },
    { district: 'Dhaka', area: 'Moddho Para (Khilkhet)' },
    { district: 'Dhaka', area: 'Nikunja(Dhaka)' },
    { district: 'Dhaka', area: 'Moddhopara(Dakshinkhan)' },
    { district: 'Dhaka', area: 'Hajipara (Rampura)' },
    { district: 'Dhaka', area: 'Kawla(Dhaka)' },
    { district: 'Dhaka', area: 'Naddapara (Dakshinkhan)' },
    { district: 'Dhaka', area: 'Bashundhara R/A (Basundhara)' },
    { district: 'Dhaka', area: 'Dorji Bari (Khilkhet)' },
    { district: 'Dhaka', area: 'Nadda (Baridhara)' },
    { district: 'Dhaka', area: 'Baridhara Diplomatic Zone' },
    { district: 'Dhaka', area: 'Baridhara DOHS' },
    { district: 'Dhaka', area: 'Notun Bazar (Vatara)' },
    { district: 'Dhaka', area: 'Adarsha Nagar (Middle Badda)' },
    { district: 'Dhaka', area: 'Jhilpar (Shahajadpur)' },
    { district: 'Dhaka', area: 'Uttor Badda' },
    { district: 'Dhaka', area: 'Middle Badda' },
    { district: 'Dhaka', area: 'South Badda' },
    { district: 'Dhaka', area: 'Merul Badda' },
    { district: 'Dhaka', area: 'Niketon(Gulshan)' },
    { district: 'Dhaka', area: 'Banani Block A' },
    { district: 'Dhaka', area: 'Banani DOHS' },
    { district: 'Dhaka', area: 'Orion More(Tejgaon)' },
    { district: 'Dhaka', area: 'Mohakhali DOHS' },
    { district: 'Dhaka', area: 'South Monipur(60-feet)' },
    { district: 'Dhaka', area: 'Shah ali bagh(Mirpur-1)' },
    { district: 'Dhaka', area: 'GMG More(Tejgaon)' },
    { district: 'Dhaka', area: 'Bashtola(Natun Bazar)' },
    { district: 'Dhaka', area: 'DIT Project (Merul Badda)' },
    { district: 'Dhaka', area: 'Aftabnagar(Dhaka)' },
    { district: 'Dhaka', area: 'Bijoy Shoroni(Dhaka)' },
    { district: 'Dhaka', area: 'Farmgate(Dhaka)' },
    { district: 'Dhaka', area: 'Indira Road(Firmgate)' },
    { district: 'Dhaka', area: 'Love Road (Tejgoan)' },
    { district: 'Dhaka', area: 'Tejkunipara(Farmgate)' },
    { district: 'Dhaka', area: 'Razabazar(Farmgate)' },
    { district: 'Dhaka', area: 'Sukrabad(Dhanmondi)' },
    { district: 'Dhaka', area: 'Panthopath(Dhaka)' },
    { district: 'Dhaka', area: 'Kalabagan(Dhaka)' },
    { district: 'Dhaka', area: 'Green Road(Dhaka)' },
    { district: 'Dhaka', area: 'Manik Mia Avenue(Dhaka)' },
    { district: 'Dhaka', area: 'Asad Avenue(Dhaka)' },
    { district: 'Dhaka', area: 'Jigatola(Dhanmondi)' },
    { district: 'Dhaka', area: 'Shankar (West Dhanmondi)' },
    { district: 'Dhaka', area: 'Rayer Bazar(Mohammadpur)' },
    { district: 'Dhaka', area: 'Tallabag(Dhanmondi)' },
    { district: 'Dhaka', area: 'Hazaribag(Dhaka)' },
    { district: 'Dhaka', area: 'Pilkhana(Dhaka)' },
    { district: 'Dhaka', area: 'Kellar Mor(Lalbagh-Dhaka)' },
    { district: 'Dhaka', area: 'New Market(Dhaka)' },
    { district: 'Dhaka', area: 'Azimpur(Dhaka)' },
    { district: 'Dhaka', area: 'Nilkhet(Dhaka)' },
    { district: 'Dhaka', area: 'Lalbagh(Dhaka)' },
    { district: 'Dhaka', area: 'Chawkbazar (Puran Dhaka)' },
    { district: 'Dhaka', area: 'Naya Bazar (Puran Dhaka)' },
    { district: 'Dhaka', area: 'Tatibazar (Puran Dhaka)' },
    { district: 'Dhaka', area: 'Luxmi Bazar (Puran Dhaka)' },
    { district: 'Dhaka', area: 'Tipu Sultan Road(Puran Dhaka)' },
    { district: 'Dhaka', area: 'Siddique Bazar (Puran Dhaka)' },
    { district: 'Dhaka', area: 'Tikatuly (Dhaka)' },
    { district: 'Dhaka', area: 'Motijheel(Dhaka)' },
    { district: 'Dhaka', area: 'Nawabpur (Puran Dhaka)' },
    { district: 'Dhaka', area: 'Kaptan Bazar (Puran Dhaka)' },
    { district: 'Dhaka', area: 'Gulistan(Dhaka)' },
    { district: 'Dhaka', area: 'Bongo Bazar(Puran Dhaka)' },
    { district: 'Dhaka', area: 'Chankarpul(Puran Dhaka)' },
    { district: 'Dhaka', area: 'Palashi(Dhaka)' },
    { district: 'Dhaka', area: 'Dhakeshwari(Dhaka)' },
    { district: 'Dhaka', area: 'Kamalapur(Dhaka)' },
    { district: 'Dhaka', area: 'Wari (Puran Dhaka)' },
    { district: 'Dhaka', area: 'Narinda (Puran Dhaka)' },
    { district: 'Dhaka', area: 'Dainik Bangla Mor(Paltan)' },
    { district: 'Dhaka', area: 'Fakirapul (Dhaka)' },
    { district: 'Dhaka', area: 'Kakrail (Dhaka)' },
    { district: 'Dhaka', area: 'Naya Paltan (Dhaka)' },
    { district: 'Dhaka', area: 'Bijoynagar (Paltan)' },
    { district: 'Dhaka', area: 'Press Club (Dhaka)' },
    { district: 'Dhaka', area: 'High Court (Dhaka)' },
    { district: 'Dhaka', area: 'Dhaka University' },
    { district: 'Dhaka', area: 'Dhaka Medical College' },
    { district: 'Dhaka', area: 'Bongo Bondhu Avenue (Puran Dhaka)' },
    { district: 'Dhaka', area: 'Kazi Nazrul Islam Avenue(Dhaka)' },
    { district: 'Dhaka', area: 'Kawran Bazar(Dhaka)' },
    { district: 'Dhaka', area: 'Minto Road (Dhaka)' },
    { district: 'Dhaka', area: 'Shantinagar (Dhaka)' },
    { district: 'Dhaka', area: 'Shantibag (Dhaka)' },
    { district: 'Dhaka', area: 'Baily Road (Dhaka)' },
    { district: 'Dhaka', area: 'Minto Road(Dhaka)' },
    { district: 'Dhaka', area: 'BSMMU Hospital-Shahbag(Dhaka)' },
    { district: 'Dhaka', area: 'Eskaton Garden Road(Dhaka)' },
    { district: 'Dhaka', area: 'Eskaton(Dhaka)' },
    { district: 'Dhaka', area: 'Moghbazar(Dhaka)' },
    { district: 'Dhaka', area: 'Mouchak (Malibagh)' },
    { district: 'Dhaka', area: 'Malibagh (Dhaka)' },
    { district: 'Dhaka', area: 'Rampura(Dhaka)' },
    { district: 'Dhaka', area: 'Shahbag(Dhaka)' },
    { district: 'Dhaka', area: 'Katabon(Dhaka)' },
    { district: 'Dhaka', area: 'Hatirpool(Dhaka)' },
    { district: 'Dhaka', area: 'Bashabo(Dhaka)' },
    { district: 'Dhaka', area: 'Khilgaon(Dhaka)' },
    { district: 'Dhaka', area: 'Middle Bashabo(Dhaka)' },
    { district: 'Dhaka', area: 'Goran(Dhaka)' },
    { district: 'Dhaka', area: 'Madartek(Dhaka)' },
    { district: 'Dhaka', area: 'Manik Nagar (Dhaka)' },
    { district: 'Dhaka', area: 'Shahjahanpur(Dhaka)' },
    { district: 'Dhaka', area: 'Banasree(Dhaka)' },
    { district: 'Dhaka', area: 'Meradia(Dhaka)' },
    { district: 'Dhaka', area: 'Boroitola Bazar (Natun Bazar)' },
    { district: 'Narayanganj', area: 'Bhulta (Rupganj)' },
    { district: 'Dhaka', area: 'Mugda (Dhaka)' },
    { district: 'Dhaka', area: 'Golapbag (Dhaka)' },
    { district: 'Dhaka', area: 'Jatrabari(Dhaka)' },
    { district: 'Dhaka', area: 'Hatirjheel Thana (Dhaka)' },
    { district: 'Dhaka', area: 'Bangla Motor(Dhaka)' },
    { district: 'Dhaka', area: 'Paribag(Dhaka)' },
    { district: 'Dhaka', area: 'Bakshibazar (Puran Dhaka)' },
    { district: 'Dhaka', area: 'Elephant Road(Dhaka)' },
    { district: 'Dhaka', area: 'Kathalbagan(Dhaka)' },
    { district: 'Dhaka', area: 'Malibagh Taltola(Dhaka)' },
    { district: 'Dhaka', area: 'Central Road(Dhanmodi)' },
    { district: 'Dhaka', area: 'Sabujbag Thana(Dhaka)' },
    { district: 'Dhaka', area: 'Habibullah Bahar University(Dhaka)' },
    { district: 'Dhaka', area: 'Dolaikhal (Puran Dhaka)' },
    { district: 'Dhaka', area: 'Shegunbagicha (Dhaka)' },
    { district: 'Dhaka', area: 'Rajarbag police lines(Dhaka)' },
    { district: 'Dhaka', area: 'Babubazar (Puran Dhaka)' },
    { district: 'Dhaka', area: 'Islampur(Puran Dhaka)' },
    { district: 'Dhaka', area: 'Imamgonj (Puran Dhaka)' },
    { district: 'Dhaka', area: 'Nayabazar  (Dhaka)' },
    { district: 'Dhaka', area: 'Zigatola(Dhanmodi)' },
    { district: 'Dhaka', area: 'West Kazipara(Mirpur)' },
    { district: 'Dhaka', area: 'West Shewrapara(Mirpur)' },
    { district: 'Dhaka', area: 'Kalshi(Mirpur)' },
    { district: 'Dhaka', area: 'Sutrapur (Puran Dhaka)' },
    { district: 'Dhaka', area: 'Kamrangichar(Dhaka)' },
    { district: 'Dhaka', area: 'Purana Paltan (Dhaka)' },
    { district: 'Dhaka', area: 'Shyampur(Jatrabari)' },
    { district: 'Dhaka', area: 'Dholaipar(Puran Dhaka)' },
    { district: 'Dhaka', area: 'Monipuri Para(Farmgate)' },
    { district: 'Dhaka', area: 'Bosila Bridge(Dhaka)' },
    { district: 'Dhaka', area: 'Shonir Akhra(Dhaka)' },
    { district: 'Dhaka', area: 'Mirpur 2 (Dhaka )' },
    { district: 'Dhaka', area: 'Bongshal (Puran Dhaka)' },
    { district: 'Dhaka', area: 'Siddweswari (Dhaka)' },
    { district: 'Dhaka', area: 'Nakhalpara (Tejgoan)' },
    { district: 'Dhaka', area: 'Sector 18 (Uttara)' },
    { district: 'Dhaka', area: 'Joar Shahara (Kuril)' },
    { district: 'Dhaka', area: 'Science Lab(Dhaka)' },
    { district: 'Dhaka', area: 'Sobhanbag(Dhanmondi)' },
    { district: 'Dhaka', area: 'ECB Chattar(Mirpur)' },
    { district: 'Dhaka', area: 'Arambag (Motijheel)' },
    { district: 'Dhaka', area: 'Armanitola (Puran Dhaka)' },
    { district: 'Dhaka', area: 'Islambag (Puran Dhaka)' },
    { district: 'Dhaka', area: 'Kamarpara(Uttara)' },
    { district: 'Dhaka', area: 'Mitford (Puran Dhaka)' },
    { district: 'Dhaka', area: 'Shakhari Bazar (Puran Dhaka)' },
    { district: 'Dhaka', area: 'Katherpol (Puran Dhaka)' },
    { district: 'Dhaka', area: 'Bangla Bazar  (Puran Dhaka)' },
    { district: 'Dhaka', area: 'Patuatuly (Puran Dhaka)' },
    { district: 'Dhaka', area: 'Nandipara(Dhaka)' },
    { district: 'Dhaka', area: 'Nazira Bazar (Puran Dhaka)' },
    { district: 'Dhaka', area: 'Gopibag Motijheel(Dhaka)' },
    { district: 'Dhaka', area: 'Shwamibag(Dhaka)' },
    { district: 'Dhaka', area: 'Sayedabad(Dhaka)' },
    { district: 'Dhaka', area: 'Sadarghat Dhaka' },
    { district: 'Dhaka', area: 'Kaltabazar (Puran Dhaka)' },
    { district: 'Dhaka', area: 'Jurain(Dhaka)' },
    { district: 'Dhaka', area: 'Gendaria (Puran Dhaka)' },
    { district: 'Dhaka', area: 'RayerBag(Dhaka)' },
    { district: 'Dhaka', area: 'Faridabad (Jatrabari)' },
    { district: 'Dhaka', area: 'Matuail (Jatrabari)' },
    { district: 'Dhaka', area: 'Doniya (Dhaka)' },
    { district: 'Dhaka', area: 'Postogola (Jurain-Dhaka)' },
    { district: 'Dhaka', area: 'Konapara (Demra)' },
    { district: 'Dhaka', area: 'Dhaka Uddyan(Mohammadpur)' },
    { district: 'Dhaka', area: 'Shekhertek(Mohammadpur)' },
    { district: 'Dhaka', area: 'CWH' },
    { district: 'Dhaka', area: 'Taltola-Agargaon(Dhaka)' },
    { district: 'Dhaka', area: 'Manda(Dhaka)' },
    { district: 'Dhaka', area: 'Zoo Road(Dhaka)' },
    { district: 'Dhaka', area: 'Dhaka uddan(Mohammadpur)' },
    { district: 'Dhaka', area: 'Nobodoy(Mohammadpur)' },
    { district: 'Dhaka', area: 'Chad Uddan(Mohammadpur)' },
    { district: 'Dhaka', area: 'Mohammadia Housing(Mohammadpur)' },
    { district: 'Dhaka', area: 'Ring Road(Shymoli)' },
    { district: 'Dhaka', area: 'Tajmahal Road(Mohammadpur)' },
    { district: 'Dhaka', area: 'Nurjahan Road(Mohammadpur)' },
    { district: 'Dhaka', area: 'Rajia Sultana Road(Mohammadpur)' },
    { district: 'Dhaka', area: 'Sector 4 (Uttara)' },
    { district: 'Dhaka', area: 'Adam Ali Market(Mazar Road-Mirpur)' },
    { district: 'Dhaka', area: 'Chalabon(Dakshinkhan)' },
    { district: 'Dhaka', area: 'Mollapara(Dakhinkhan )' },
    { district: 'Dhaka', area: 'East Azampur (Uttara)' },
    { district: 'Dhaka', area: 'Sector 5 (Uttara)' },
    { district: 'Dhaka', area: 'Sector 14 (Uttara)' },
    { district: 'Dhaka', area: 'Sector 3 (Uttara)' },
    { district: 'Dhaka', area: 'Sector 7 (Uttara)' },
    { district: 'Dhaka', area: 'Sector 9 (Uttara)' },
    { district: 'Dhaka', area: 'Sector 11(Uttara)' },
    { district: 'Dhaka', area: 'Nalbhog(Uttara)' },
    { district: 'Dhaka', area: 'Middle Azampur (Uttara)' },
    { district: 'Dhaka', area: 'Turag Model School (Uttara)' },
    { district: 'Dhaka', area: 'Dhour (Uttara )' },
    { district: 'Dhaka', area: 'Bhatuliya(Uttara)' },
    { district: 'Dhaka', area: 'Bamnartek(Uttara)' },
    { district: 'Dhaka', area: 'Turag Thana(Uttara)' },
    { district: 'Dhaka', area: 'Khalek Filling Station Road(Kallyanpur)' },
    { district: 'Dhaka', area: 'Lalkuthi (Mazar road-Mirpur)' },
    { district: 'Dhaka', area: 'Mirpur-1-block-A(Dhaka)' },
    { district: 'Dhaka', area: 'Tolarbag(Mirpur)' },
    { district: 'Dhaka', area: 'Ahmed Nagar-Paikpara(Mirpur-1)' },
    { district: 'Dhaka', area: 'Paikpara (Mirpur-1)' },
    { district: 'Dhaka', area: 'Pirerbag-60-feet(Mirpur)' },
    { district: 'Dhaka', area: 'Mirpur-1-block-B (Dhaka)' },
    { district: 'Dhaka', area: 'Dewanpara -vasantek(Mirpur)' },
    { district: 'Dhaka', area: 'Begunbari(Tejgaon)' },
    { district: 'Dhaka', area: 'Ajiz Market-ECB Chattar(Mirpur)' },
    { district: 'Dhaka', area: 'Aga Nagar(Keraniganj)' },
    { district: 'Dhaka', area: 'Kunipara (Tejgoan)' },
    { district: 'Dhaka', area: 'Babli Masjid (Tejgoan)' },
    { district: 'Dhaka', area: 'Kaderabad Housing(Mohammadpur)' },
    { district: 'Dhaka', area: 'Kunia-Tar gach(Tongi)' },
    { district: 'Dhaka', area: 'Gacha Bazar ( Boro Bari)' },
    { district: 'Dhaka', area: 'Boro Bari (Tongi)' },
    { district: 'Dhaka', area: 'Board Bazar (Tongi)' },
    { district: 'Dhaka', area: 'Kamarjuri (Gazipur)' },
    { district: 'Dhaka', area: 'Saifuddin Sarkar Academy Road (Tongi collage Gate)' },
    { district: 'Dhaka', area: 'Ershadnagar-Hossain Market(Tongi)' },
    { district: 'Dhaka', area: 'Sataish-Gazipura(Tongi)' },
    { district: 'Dhaka', area: 'Apollo Hospital (Bashundhara R/A)' },
    { district: 'Dhaka', area: 'Nurerchala(Natun Bazar)' },
    { district: 'Dhaka', area: 'Bawaila Para(Khilkhet)' },
    { district: 'Dhaka', area: 'Satarkul (Uttor Badda)' },
    { district: 'Dhaka', area: '100 Feet Road (Natun Bazar)' },
    { district: 'Dhaka', area: 'Buddho Mondir(Dhaka)' },
    { district: 'Dhaka', area: 'Sipahibag(Dhaka)' },
    { district: 'Dhaka', area: 'TT Para (Dhaka)' },
    { district: 'Dhaka', area: 'Eastern Housing (Mohammadpur)' },
    { district: 'Dhaka', area: 'Tenari More (Dhaka)' },
    { district: 'Dhaka', area: 'Shahidnagar (Lalbagh- Dhaka)' },
    { district: 'Dhaka', area: 'Jhigatola(Dhanmondi)' },
    { district: 'Dhaka', area: 'Polashi(Dhaka)' },
    { district: 'Dhaka', area: 'Satmoshjid Road(Dhaka)' },
    { district: 'Dhaka', area: 'BNP Bazar(Agargaon)' },
    { district: 'Dhaka', area: 'Kalachandpur(Nadda)' },
    { district: 'Dhaka', area: 'Nadda,Jogonnathpur' },
    { district: 'Dhaka', area: 'Kuratoli Bazar(Kuril)' },
    { district: 'Dhaka', area: 'Alatunnessa School Road (South Badda)' },
    { district: 'Dhaka', area: 'Purbo Rampura(Dhaka)' },
    { district: 'Dhaka', area: 'Bou Bazar Korail (Mohakhali)' },
    { district: 'Dhaka', area: 'Chairman Bari (Banani)' },
    { district: 'Dhaka', area: 'Confidence Tower (Shahajadpur)' },
    { district: 'Dhaka', area: 'Dhelna (Khilkhet)' },
    { district: 'Dhaka', area: 'Madani Avenue(100 Feet Road Natun Bazar)' },
    { district: 'Dhaka', area: 'Korail (Mohakhali)' },
    { district: 'Dhaka', area: 'Mahanogor(Dhaka)' },
    { district: 'Dhaka', area: 'Nimtola (Merul Badda)' },
    { district: 'Dhaka', area: 'Boat Ghat Road (Natun Bazar)' },
    { district: 'Dhaka', area: 'Pastola Bazar (Merul Badda)' },
    { district: 'Dhaka', area: 'Poschim Badda' },
    { district: 'Dhaka', area: 'Purbo Badda' },
    { district: 'Dhaka', area: 'Sat-tola Bazar (Mohakhali)' },
    { district: 'Dhaka', area: 'Shaheenbagh (Tejgoan)' },
    { district: 'Dhaka', area: 'Suvastu Nazar Valley (Shahjadpur)' },
    { district: 'Dhaka', area: 'ICDDRB (Mohakhali)' },
    { district: 'Dhaka', area: 'Satrasta (Tejgoan)' },
    { district: 'Dhaka', area: 'Shadinota Sharani (Uttor Badda)' },
    { district: 'Dhaka', area: 'North Badda' },
    { district: 'Dhaka', area: 'Wireless gate (Mohakhali)' },
    { district: 'Dhaka', area: 'Solmaid(Natun Bazar)' },
    { district: 'Dhaka', area: 'Pink City Model Town (Kuril )' },
    { district: 'Dhaka', area: 'Mirhazirbagh(Jatrabari)' },
    { district: 'Dhaka', area: 'Mahut Tuli (Puran Dhaka)' },
    { district: 'Dhaka', area: 'Alubazar (Puran Dhaka)' },
    { district: 'Dhaka', area: 'Badam Toli (Babubazar)' },
    { district: 'Dhaka', area: 'Chamelibag (Dhaka)' },
    { district: 'Dhaka', area: 'Doyagonj (Jatrabari)' },
    { district: 'Dhaka', area: 'Farashgong (Puran Dhaka)' },
    { district: 'Dhaka', area: 'Dholpur(Jatrabari)' },
    { district: 'Dhaka', area: 'Kodomtoli(Keraniganj)' },
    { district: 'Dhaka', area: 'Kotwali Thana (Puran Dhaka)' },
    { district: 'Dhaka', area: 'Railway Colony (Puran Dhaka)' },
    { district: 'Dhaka', area: 'Rajar Dewri (Puran Dhaka)' },
    { district: 'Dhaka', area: 'Sat rowja (Puran Dhaka)' },
    { district: 'Dhaka', area: 'Tantibazar (Puran Dhaka)' },
    { district: 'Dhaka', area: 'Rosulbagh(Mohakhali)' },
    { district: 'Dhaka', area: 'Gopalpur (Tongi Station Road)' },
    { district: 'Dhaka', area: 'Tongi College Gate' },
    { district: 'Dhaka', area: 'Badekomelosshor (Board Bazar)' },
    { district: 'Dhaka', area: 'Megh Dubi Tongi ( Mirer Bazar)' },
    { district: 'Dhaka', area: 'Mazar Road Uttarkhan' },
    { district: 'Dhaka', area: 'Sonakhola (Dakshinkhan)' },
    { district: 'Dhaka', area: 'Hajipara(Dakshinkhan)' },
    { district: 'Dhaka', area: 'Ranavola(Uttara)' },
    { district: 'Dhaka', area: 'Joynal Market(Dakshinkhan)' },
    { district: 'Dhaka', area: 'Haji Camp(Askona)' },
    { district: 'Dhaka', area: 'Sarwar Avenue(Dakshinkhan)' },
    { district: 'Dhaka', area: 'BDR Market-House Building(Uttara)' },
    { district: 'Dhaka', area: 'BDR Market-Sector 6(Uttara)' },
    { district: 'Dhaka', area: 'Moinartek(Dakshinkhan)' },
    { district: 'Dhaka', area: 'Atipara(Dakshinkhan)' },
    { district: 'Dhaka', area: 'Kotbari (Dakshinkhan)' },
    { district: 'Dhaka', area: 'Dewan City(Dakshinkhan)' },
    { district: 'Dhaka', area: 'Mollartek(Dakshinkhan)' },
    { district: 'Dhaka', area: 'Gawair(Dakshinkhan)' },
    { district: 'Dhaka', area: 'Kosaibari (Dakshinkhan)' },
    { district: 'Dhaka', area: 'Prembagan(Dakshinkhan)' },
    { district: 'Dhaka', area: 'Kachkura(Dakshinkhan)' },
    { district: 'Dhaka', area: 'Helal Market(Dakshinkhan)' },
    { district: 'Dhaka', area: 'Chamur Khan(Dakshinkhan)' },
    { district: 'Dhaka', area: 'Army housing Society(Dakshinkhan)' },
    { district: 'Dhaka', area: 'Ismailkholla(Dakshinkhan)' },
    { district: 'Dhaka', area: 'Masterpara(Dakshinkhan)' },
    { district: 'Dhaka', area: 'Khilgaon C Block (Dhaka)' },
    { district: 'Dhaka', area: 'Barua(Dakshinkhan)' },
    { district: 'Dhaka', area: 'Namapara (Khilkhet)' },
    { district: 'Dhaka', area: 'Ahalia (Uttara Sector-14)' },
    { district: 'Dhaka', area: 'Ainusbag-Dakshinkhan' },
    { district: 'Dhaka', area: 'Diabari (Uttara sector-18)' },
    { district: 'Dhaka', area: 'Habib Market (Uttara Sector-5)' },
    { district: 'Dhaka', area: 'Pakuria Bazar (Uttara)' },
    { district: 'Dhaka', area: 'Jahurul Islam Avenue (Aftabnagar)' },
    { district: 'Dhaka', area: 'Gulbagh(Dhaka)' },
    { district: 'Dhaka', area: 'Meradiya Bazar(Dhaka)' },
    { district: 'Dhaka', area: 'Mirbagh(Dhaka)' },
    { district: 'Dhaka', area: 'Modhubagh(Dhaka)' },
    { district: 'Dhaka', area: 'Rampura TV center(Dhaka)' },
    { district: 'Dhaka', area: 'TB gate (Mohakhali)' },
    { district: 'Dhaka', area: 'Ulan road(Dhaka)' },
    { district: 'Dhaka', area: 'Mirpur 10 Circle(Mirpur)' },
    { district: 'Dhaka', area: 'Mirpur-1-block-C (Dhaka)' },
    { district: 'Dhaka', area: 'Bazar Road - Manikdi(Mirpur)' },
    { district: 'Dhaka', area: 'Police Staff College(Mirpur)' },
    { district: 'Dhaka', area: 'Technical (Kallayanpur)' },
    { district: 'Dhaka', area: 'NAM Garden-BRTA (Mirpur-13)' },
    { district: 'Dhaka', area: 'Benaroshi Polli(Mirpur)' },
    { district: 'Dhaka', area: 'Tamanna Park(Beribadh-Mirpur)' },
    { district: 'Dhaka', area: 'Buddhijibi (Mazar Road-Mirpur)' },
    { district: 'Dhaka', area: 'Hope School Road (Mirpur-13)' },
    { district: 'Dhaka', area: 'Buddhist Temple(Mirpur-13)' },
    { district: 'Dhaka', area: 'Palasnagor(Mirpur 11)' },
    { district: 'Dhaka', area: 'Purobi Bus Stand(Mirpur)' },
    { district: 'Dhaka', area: 'Govt Secondary School Road Rupnagor(Mirpur)' },
    { district: 'Dhaka', area: 'Senpara Parbata(Mirpur 10)' },
    { district: 'Dhaka', area: 'BRTA(Mirpur)' },
    { district: 'Dhaka', area: 'South Kafrul (Mirpur)' },
    { district: 'Dhaka', area: 'Niketon Bazar Gate (Niketon)' },
    { district: 'Dhaka', area: 'Eastern Housing (Mirpur-12)' },
    { district: 'Dhaka', area: 'Lucas more(Tejgaon)' },
    { district: 'Dhaka', area: 'Nijhum gate (Dhaka Cantonment)' },
    { district: 'Dhaka', area: 'Niketon Bazar gate(Mohakhali)' },
    { district: 'Dhaka', area: 'South Begunbari(Tejgaon)' },
    { district: 'Dhaka', area: 'Mohakhali Bus terminal(Mohakhali)' },
    { district: 'Dhaka', area: 'Arambag (Mirpur 7)' },
    { district: 'Dhaka', area: 'Nazimuddin Road (Puran Dhaka)' },
    { district: 'Dhaka', area: 'Nazimuddin Road (Malibag)' },
    { district: 'Dhaka', area: 'Kodomtoli Thana (Jatrabari)' },
    { district: 'Dhaka', area: 'SDA' },
    { district: 'Dhaka', area: '60 feet Mor (Mirpur-2 )' },
    { district: 'Dhaka', area: 'Banasree Block - A (Dhaka)' },
    { district: 'Dhaka', area: 'Banasree Block - B (Dhaka)' },
    { district: 'Dhaka', area: 'Banasree Block - C (Dhaka)' },
    { district: 'Dhaka', area: 'Banasree Block - D (Dhaka)' },
    { district: 'Dhaka', area: 'Banasree Block - E (Dhaka)' },
    { district: 'Dhaka', area: 'Banasree Block - F (Dhaka)' },
    { district: 'Dhaka', area: 'Banasree Block - G (Dhaka)' },
    { district: 'Dhaka', area: 'Banasree Block - H (Dhaka)' },
    { district: 'Dhaka', area: 'Banasree Block - I (Dhaka)' },
    { district: 'Dhaka', area: 'Banasree Block - J (Dhaka)' },
    { district: 'Dhaka', area: 'Banasree Block - K (Dhaka)' },
    { district: 'Dhaka', area: 'Banasree Block - L (Dhaka)' },
    { district: 'Dhaka', area: 'Banasree Block - M (Dhaka)' },
    { district: 'Dhaka', area: 'Banasree Block - N (Dhaka)' },
    { district: 'Dhaka', area: 'Sector 1 (Uttara)' },
    { district: 'Dhaka', area: 'Sector 2 (Uttara)' },
    { district: 'Dhaka', area: 'Sector  6 (Uttara)' },
    { district: 'Dhaka', area: 'Sector 8 (Uttara)' },
    { district: 'Dhaka', area: 'Sector 10 (Uttara)' },
    { district: 'Dhaka', area: 'Sector 12(Uttara)' },
    { district: 'Dhaka', area: 'Uttara Sector - 13' },
    { district: 'Dhaka', area: 'Sector 15(Uttara)' },
    { district: 'Dhaka', area: 'Dhanmondi - Rd 1' },
    { district: 'Dhaka', area: 'Dhanmondi - Rd 2' },
    { district: 'Dhaka', area: 'Dhanmondi - Road 4' },
    { district: 'Dhaka', area: 'Dhanmondi - Road 4A' },
    { district: 'Dhaka', area: 'Dhanmondi - Rd 6' },
    { district: 'Dhaka', area: 'Dhanmondi - Rd 3A' },
    { district: 'Dhaka', area: 'Dhanmondi - Rd 6A' },
    { district: 'Dhaka', area: 'Dhanmondi - Rd 8' },
    { district: 'Dhaka', area: 'Dhanmondi - Rd 8A' },
    { district: 'Dhaka', area: 'Dhanmondi - Rd 9' },
    { district: 'Dhaka', area: 'Dhanmondi - Road 9/A' },
    { district: 'Dhaka', area: 'Dhanmondi - Rd 10' },
    { district: 'Dhaka', area: 'Dhanmondi - Rd 12' },
    { district: 'Dhaka', area: 'Dhanmondi - Rd 12A' },
    { district: 'Dhaka', area: 'Dhanmondi - Rd 15' },
    { district: 'Dhaka', area: 'Dhanmondi - Rd 15 A' },
    { district: 'Dhaka', area: 'Dhanmondi - Rd 27' },
    { district: 'Dhaka', area: 'Dhanmondi - Rd 28' },
    { district: 'Dhaka', area: 'Dhanmondi - Rd 29' },
    { district: 'Dhaka', area: 'Jigatala post office(Dhanmondi)' },
    { district: 'Dhaka', area: 'Sadek Khan Road(Mohammadpur)' },
    { district: 'Dhaka', area: 'Sher e Bangla Road(Mohammadpur)' },
    { district: 'Dhaka', area: 'Katasur(Mohammadpur)' },
    { district: 'Dhaka', area: 'Dhanmondi Staff Quarter' },
    { district: 'Dhaka', area: 'Sector 16 (Uttara)' },
    { district: 'Dhaka', area: 'Sector 17 (Uttara)' },
    { district: 'Dhaka', area: 'Arshinagar (Keraniganj)' },
    { district: 'Dhaka', area: 'Washpur(Keraniganj)' },
    { district: 'Dhaka', area: 'Garden City(Mohammadpur)' },
    { district: 'Dhaka', area: 'Boddhovumi(Mohammadpur)' },
    { district: 'Dhaka', area: 'Mirpur - 6(Mirpur)' },
    { district: 'Dhaka', area: 'Mirpur - 7(Mirpur)' },
    { district: 'Dhaka', area: 'Mirpur 11(Dhaka)' },
    { district: 'Dhaka', area: 'Mirpur  11.5 Bus Stand(Dhaka)' },
    { district: 'Dhaka', area: 'Mirpur 12(Dhaka)' },
    { district: 'Dhaka', area: 'Mirpur - 13(Mirpur)' },
    { district: 'Dhaka', area: 'Mirpur - 15(Mirpur)' },
    { district: 'Dhaka', area: 'Mirpur  14 (Dhaka)' },
    { district: 'Dhaka', area: 'Nikunja 2 (Dhaka)' },
    { district: 'Gazipur', area: 'Jalsukha -Baroipara (Kaliakoir)' },
    { district: 'Dhaka', area: 'Banani Block B' },
    { district: 'Dhaka', area: 'Banani Block C' },
    { district: 'Dhaka', area: 'Banani Block D' },
    { district: 'Dhaka', area: 'Banani Block E' },
    { district: 'Dhaka', area: 'Banani Block F' },
    { district: 'Dhaka', area: 'Banani Block G' },
    { district: 'Dhaka', area: 'Banani Block H' },
    { district: 'Dhaka', area: 'Banani Block I' },
    { district: 'Dhaka', area: 'Banani Block J' },
    { district: 'Dhaka', area: 'Banani Block K' },
    { district: 'Dhaka', area: 'Banani Block L' },
    { district: 'Dhaka', area: 'Baridhara J block' },
    { district: 'Dhaka', area: 'Baridhara K block' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-3' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-4' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-5' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-6' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-7' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-8' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-9' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-10' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-11' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-12' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-13' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-14' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-15' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-16' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-17' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-18' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-19' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-20' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-21' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-22' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-23' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-24' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-25' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-26' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-27' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-28' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-29' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-30' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-31' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-32' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-123' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-124' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-125' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-126' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-127' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-128' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-129' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-130' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-131' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-132' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-133' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-134' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-135' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-136' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-137' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-138' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-139' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-140' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-141' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-143' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-144' },
    { district: 'Dhaka', area: 'DNCC Market (Gulshan 1)' },
    { district: 'Dhaka', area: 'Police plaza (Gulshan 1)' },
    { district: 'Dhaka', area: 'Gulshan-1 Road-142' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-33' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-34' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-35' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-36' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-37' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-38' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-39' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-40' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-41' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-42' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-43' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-44' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-45' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-46' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-47' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-48' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-49' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-50' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-51' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-52' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-53' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-54' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-55' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-56' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-57' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-58' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-59' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-60' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-61' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-62' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-63' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-64' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-65' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-66' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-67' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-68' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-69' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-70' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-71' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-72' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-73' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-74' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-75' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-76' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-77' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-78' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-79' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-80' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-81' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-82' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-83' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-84' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-85' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-86' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-87' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-88' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-89' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-90' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-91' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-92' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-93' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-94' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-95' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-96' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-97' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-98' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-99' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-100' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-101' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-102' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-103' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-104' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-105' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-106' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-107' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-108' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-109' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-110' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-111' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-112' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-113' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-114' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-115' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-116' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-117' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-118' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-119' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-120' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-121' },
    { district: 'Dhaka', area: 'Gulshan-2 Road-122' },
    { district: 'Dhaka', area: 'DNCC Market (Gulshan 2)' },
    { district: 'Munshiganj', area: 'Voberchar  ( Munshiganj )' },
    { district: 'Munshiganj', area: 'Jamaldi  ( Munshiganj )' },
    { district: 'Munshiganj', area: 'Hossaindi  ( Munshiganj )' },
    { district: 'Munshiganj', area: 'Bausia  ( Munshiganj )' },
    { district: 'Dhaka', area: 'Mirpur-1-block-D (Dhaka)' },
    { district: 'Dhaka', area: 'Mirpur-1-block-E (Dhaka)' },
    { district: 'Dhaka', area: 'Mirpur-1-block-F (Dhaka)' },
    { district: 'Dhaka', area: 'Mirpur-1-block-G (Dhaka)' },
    { district: 'Dhaka', area: 'Mirpur-1-block-H (Dhaka)' },
    { district: 'Dhaka', area: 'Mirpur-1-block-New - C (Dhaka)' },
    { district: 'Dhaka', area: 'Dakkhin Bisil (Mirpur-1)' },
    { district: 'Dhaka', area: 'Uttor Bisil (Mirpur-1)' },
    { district: 'Dhaka', area: 'kiyangshi chinese (Mirpur-1)' },
    { district: 'Dhaka', area: 'Shah Ali Market (Mirpur-1)' },
    { district: 'Dhaka', area: 'East Kazipara(Mirpur)' },
    { district: 'Dhaka', area: 'Purbo Monipur (Mirpur)' },
    { district: 'Dhaka', area: 'Poschim Monipur (Mirpur)' },
    { district: 'Dhaka', area: 'West Kafrul (Agargaon)' },
    { district: 'Dhaka', area: 'Boat Ghat Road (Khilkhet)' },
    { district: 'Dhaka', area: 'Lake City Park (Khilkhet)' },
    { district: 'Dhaka', area: 'Khapara (Khilkhet)' },
    { district: 'Dhaka', area: 'Dumni (Khilkhet)' },
    { district: 'Dhaka', area: 'Patira Bazar (Khilkhet)' },
    { district: 'Dhaka', area: 'Mostul Check post (Khilkhet)' },
    { district: 'Dhaka', area: 'Kurmitoal General Hospital' },
    { district: 'Dhaka', area: 'Soinik Club (Dhaka Cantonment)' },
    { district: 'Dhaka', area: 'Arjotpara(Mohakhali)' },
    { district: 'Dhaka', area: 'BAF Shaheen College(Dhaka Cantonment)' },
    { district: 'Dhaka', area: 'BNS Haji Mohsin(Dhaka Cantonment)' },
    { district: 'Dhaka', area: 'BAF Eagle hall(Dhaka Cantonment)' },
    { district: 'Dhaka', area: 'Shahid Moinul Road (Dhaka Cantonment)' },
    { district: 'Dhaka', area: 'Shaheed Sharani(Dhaka Cantonment)' },
    { district: 'Dhaka', area: 'Sena Malancha(Dhaka Cantonment)' },
    { district: 'Dhaka', area: 'Adamjee Cantonment College(Dhaka Cantonment)' },
    { district: 'Dhaka', area: 'Army officers Club(Dhaka Cantonment)' },
    { district: 'Dhaka', area: 'Dhaka Cantonment post office' },
    { district: 'Dhaka', area: 'Kurmitola(Dhaka Cantonment)' },
    { district: 'Dhaka', area: 'CMH(Dhaka Cantonment)' },
    { district: 'Dhaka', area: 'Shaheed Ramiz Uddin Gate- MES' },
    { district: 'Dhaka', area: 'Shaheed Ramiz Uddin Cantonment College' },
    { district: 'Dhaka', area: 'Kunjolota-MES(Dhaka Cantonment)' },
    { district: 'Dhaka', area: 'Armed Forces Medical institute-MES' },
    { district: 'Dhaka', area: 'Staff road officers querters-MES' },
    { district: 'Dhaka', area: 'MES Park(Dhaka Cantonment)' },
    { district: 'Dhaka', area: 'Bijoy Keton-MES(Dhaka Cantonment)' },
    { district: 'Dhaka', area: 'Nokkhotro-MES(Dhaka Cantonment)' },
    { district: 'Dhaka', area: 'Bangladesh University of Professionals(BUP)' },
    { district: 'Dhaka', area: 'Mirpur Cantonment Public School & College(Mirpur)' },
    { district: 'Dhaka', area: 'MIST(Mirpur)' },
    { district: 'Dhaka', area: 'Mirpur Cantonment(Mirpur)' },
    { district: 'Dhaka', area: 'House Building(Uttara)' },
    { district: 'Dhaka', area: 'Hazrat Shahjalal International Airport (Dhaka)' },
    { district: 'Dhaka', area: 'International Convension City(Bashundhara)' },
    { district: 'Dhaka', area: 'Banarupa Abashik(Khilkhet)' },
    { district: 'Dhaka', area: 'Sopnopuri Bashundhara R/A' },
    { district: 'Dhaka', area: 'Import Cargo Terminal (Dhaka Airport Uttara)' },
    { district: 'Dhaka', area: 'Customs House (Dhaka Airport Uttara)' },
    { district: 'Dhaka', area: 'Rajlokkhi Complex (Uttara)' },
    { district: 'Dhaka', area: 'New Paltan (Azimpur-Dhaka)' },
    { district: 'Dhaka', area: 'West Barua(Khilkhet)' },
    { district: 'Dhaka', area: 'South Barua(Khilkhet)' },
    { district: 'Dhaka', area: 'South Barua Residential Area(Khilkhet)' },
    { district: 'Dhaka', area: 'Rainkhola Bazar(Mirpur)' },
    { district: 'Dhaka', area: 'Dhaka Commerce College(Dhaka)' },
    { district: 'Dhaka', area: 'Mugda Medical College)Dhaka)' },
    { district: 'Dhaka', area: 'River View (Keraniganj)' },
    { district: 'Dhaka', area: 'Telghat (Keraniganj)' },
    { district: 'Dhaka', area: 'Ghatarchar(Keraniganj)' },
    { district: 'Dhaka', area: 'Beraid (Dhaka)' },
    { district: 'Dhaka', area: 'Dhaka International university (100-Feet-Dhaka)' },
    { district: 'Dhaka', area: 'United International University(100-feet-Dhaka)' },
    { district: 'Dhaka', area: 'Mogardia (Dhaka)' },
    { district: 'Dhaka', area: 'Modhu Bazar(Mohammadpur)' },
    { district: 'Dhaka', area: 'Baroikhali (Mohammadpur)' },
    { district: 'Savar', area: 'Savar' },
    { district: 'Savar', area: 'Nabinagar, Savar, Dhaka' },
    { district: 'Gazipur', area: 'Rail Gate (Tongi Station Road)' },
    { district: 'Demra', area: 'Demra (Dhaka)' },
    { district: 'Savar', area: 'Ashulia, Savar' },
    { district: 'Savar', area: 'Baipayl, Savar' },
    { district: 'Keranigonj', area: 'Keranigonj(Dhaka)' },
    { district: 'Dhamrai', area: 'Dhamrai' },
    { district: 'Gazipur', area: 'Kodda Bazar (Tongi)' },
    { district: 'Gazipur', area: 'Kaliakoir Upazila(Gazipur)' },
    { district: 'Gazipur', area: 'Kaliganj(Tongi)' },
    { district: 'Gazipur', area: 'Kapasia (Gazipur)' },
    { district: 'Gazipur', area: 'Sreepur Chowrasta (Mawna)' },
    { district: 'Narayanganj', area: 'Araihazar Thana' },
    { district: 'Narayanganj', area: 'Bandar (Modonpur)' },
    { district: 'Narayanganj', area: 'Chashara (Narayanganj)' },
    { district: 'Narayanganj', area: 'Rupganj Thana' },
    { district: 'Narayanganj', area: 'Sonargaon (Narayanganj)' },
    { district: 'Narayanganj', area: 'Siddhirganj (Narayanganj)' },
    { district: 'Narayanganj', area: 'Fatullah (Narayanganj)' },
    { district: 'Keraniganj', area: 'Kalatia(Keraniganj)' },
    { district: 'Dhamrai', area: 'Nolam Dhamrai' },
    { district: 'Narayanganj', area: 'Shanarpar (Narayanganj)' },
    { district: 'Savar', area: 'EPZ, Baipayl, Savar' },
    { district: 'Keraniganj', area: 'Kathuria(Keraniganj)' },
    { district: 'Keraniganj', area: 'Goljarbag(Keraniganj)' },
    { district: 'Keraniganj', area: 'Nazirabag(Keraniganj)' },
    { district: 'Keraniganj', area: 'Kaliganj (Keraniganj)' },
    { district: 'Keraniganj', area: 'Nazarganj(Keraniganj)' },
    { district: 'Keraniganj', area: 'Zinzira(Keraniganj)' },
    { district: 'Tongi', area: 'Auchpara (Tongi collage Gate)' },
    { district: 'Tongi', area: 'Cherag Ali (Tongi)' },
    { district: 'Tongi', area: 'Tongi Bus Stand' },
    { district: 'Narayanganj', area: 'Bhuigor (Narayanganj)' },
    { district: 'Keraniganj', area: 'Hasnabad(Keraniganj)' },
    { district: 'Tongi', area: 'Joy Bangla Road (Tongi)' },
    { district: 'Tongi', area: 'Bonomala (Tongi collage gate)' },
    { district: 'Tongi', area: 'Morkun (Tongi Bus Stand)' },
    { district: 'Tongi', area: 'Bhadam (Cherag Ali )' },
    { district: 'Gazipur', area: 'Bottola Road (Board Bazar)' },
    { district: 'Gazipur', area: 'Kazibari Road - Gazipura (Tongi)' },
    { district: 'Tongi', area: 'Hossain Market (Tongi)' },
    { district: 'Tongi', area: 'Open University (Tongi)' },
    { district: 'Gazipur', area: 'Joydebpur (Gazipur)' },
    { district: 'Gazipur', area: 'Dhirasrom (Joydebpur)' },
    { district: 'Gazipur', area: 'Dattapara Road (Tongi collage Gate)' },
    { district: 'Gazipur', area: 'Borobari (Gazipur)' },
    { district: 'Gazipur', area: 'Choidana (Singboard-Tongi)' },
    { district: 'Gazipur', area: 'Deger Chala (Singboard-Tongi)' },
    { district: 'Gazipur', area: 'Sahid Siddque Road (Board Bazar)' },
    { district: 'Tongi', area: 'Hariken (Tongi)' },
    { district: 'Gazipur', area: 'Khortuil (Gazipura-Tongi)' },
    { district: 'Tongi', area: 'Majukhan (Tongi Station Road)' },
    { district: 'Tongi', area: 'Milgate (Tongi Station Road)' },
    { district: 'Gazipur', area: 'National University ( Board Bazar)' },
    { district: 'Gazipur', area: 'Surtaranga (Tongi Collage Gate)' },
    { district: 'Gazipur', area: 'Targach (Tongi Boro Bari)' },
    { district: 'Tongi', area: 'Boro Dewra (Tongi Cherag Ali)' },
    { district: 'Gazipur', area: 'Mawna Chowrasta' },
    { district: 'Gazipur', area: 'Bangla Bazar (Mawna)' },
    { district: 'Gazipur', area: 'Mirjapur Masterbari(Gazipur)' },
    { district: 'Gazipur', area: 'Vobanipur(Gazipur)' },
    { district: 'Gazipur', area: 'Barmi Sreepur (Gazipur)' },
    { district: 'Gazipur', area: 'Safari Park(Gazipur)' },
    { district: 'Gazipur', area: 'Pubail(Tongi)' },
    { district: 'Gazipur', area: 'Mirerbazar(Tongi)' },
    { district: 'Gazipur', area: 'Ulokhola ( Kaliganj-Tongi)' },
    { district: 'Gazipur', area: 'Modhumita (Tongi Station Road)' },
    { district: 'Gazipur', area: 'Miraspara (Tongi Bus stand)' },
    { district: 'Gazipur', area: 'Pagar - Miraspara ( Tongi Bus Stand)' },
    { district: 'Gazipur', area: 'Jinumarket (Tongi Bus Stand)' },
    { district: 'Gazipur', area: 'T & T - (Tongi Station Road )' },
    { district: 'Gazipur', area: 'Shilmun (Tongi Station Road)' },
    { district: 'Gazipur', area: 'Mudafa (Tongi cherag Ali)' },
    { district: 'Gazipur', area: 'Khapara (Hossain Market)' },
    { district: 'Gazipur', area: 'Malakerbari (Tongi)' },
    { district: 'Gazipur', area: 'Gazipur Bypass' },
    { district: 'Gazipur', area: 'Kodda (Gazipur By Pass Road road)' },
    { district: 'Gazipur', area: 'DUET (Joydebpur)' },
    { district: 'Gazipur', area: 'Shibbari (joydebpur)' },
    { district: 'Gazipur', area: 'Shimultoli (joydebpur)' },
    { district: 'Gazipur', area: 'Jorpukur (joydebpur)' },
    { district: 'Gazipur', area: 'Salna(Gazipur)' },
    { district: 'Gazipur', area: 'Porabari Bazar (Gazipur)' },
    { district: 'Gazipur', area: 'Dhaladia Sreepur(Mawna Gazipur)' },
    { district: 'Gazipur', area: 'Hotapara (Mawan-Gazipur)' },
    { district: 'Gazipur', area: 'Bager bazar (Mawana-Gazipur)' },
    { district: 'Gazipur', area: 'Member Bari(Mawna Gazipur)' },
    { district: 'Gazipur', area: 'Gorgoria Masterbari(Sreepur Gazipur)' },
    { district: 'Gazipur', area: 'Mc Bazar (Mawna)' },
    { district: 'Gazipur', area: 'Nayanpur Sreepur (Gazipur)' },
    { district: 'Gazipur', area: 'Konabari (Gazipur)' },
    { district: 'Gazipur', area: 'Mouchak (Gazipur)' },
    { district: 'Gazipur', area: 'Kashimpur Bazar (Gazipur)' },
    { district: 'Gazipur', area: 'Shafipur (Kaliakoir-Gazipur)' },
    { district: 'Gazipur', area: 'Joyna Bazar (Sreepur Gazipur)' },
    { district: 'Gazipur', area: 'Pollibidut (Chondra)' },
    { district: 'Gazipur', area: 'Chondra (Kaliakoir)' },
    { district: 'Gazipur', area: 'Rajabari Sreepur (Gazipur)' },
    { district: 'Narayanganj', area: 'Signboard (Narayanganj)' },
    { district: 'Narayanganj', area: 'Jalkuri (Narayanganj)' },
    { district: 'Narayanganj', area: 'Sibu market ( Narayanganj)' },
    { district: 'Narayanganj', area: 'Chittagong Road (Narayanganj)' },
    { district: 'Demra', area: 'Basher pull (Demra)' },
    { district: 'Demra', area: 'Bamuail (Demra)' },
    { district: 'Demra', area: 'Sharuliya (Demra)' },
    { district: 'Demra', area: 'Rani mohol  (Demra)' },
    { district: 'Demra', area: 'Staffquater  (Demra)' },
    { district: 'Demra', area: 'Demra bazar  (Demra)' },
    { district: 'Demra', area: 'Hajinogar  (Demra)' },
    { district: 'Demra', area: 'Boxnagar  (Demra)' },
    { district: 'Demra', area: 'Badsha mia road  (Demra)' },
    { district: 'Demra', area: 'Muslimnagar  (Demra)' },
    { district: 'Gazipur', area: 'Vannara (mouchak-Gazipur)' },
    { district: 'Gazipur', area: 'Sardaganj-Kashimpur( Kaliakoir)' },
    { district: 'Gazipur', area: 'Sultan Market - Kashimpur ( Kaliakoir)' },
    { district: 'Gazipur', area: 'Baroipara (Kaliakoir)' },
    { district: 'Gazipur', area: 'Goalbari bazar (Kaliakoir)' },
    { district: 'Gazipur', area: 'Hatimara-Kashimpur(Gazipur)' },
    { district: 'Gazipur', area: 'Sultan Market Kashempur (Kaliakoir)' },
    { district: 'Gazipur', area: 'Nawjor (Gazipur)' },
    { district: 'Gazipur', area: 'Fulbaria bazar (Kaliakoir)' },
    { district: 'Gazipur', area: 'Madhobpur(Kashempur)' },
    { district: 'Gazipur', area: 'Kabirpur (Kaliakoir)' },
    { district: 'Gazipur', area: 'Walton High-Tech(Chondra)' },
    { district: 'Gazipur', area: 'Waltion Micro-Tech(Chondra)' },
    { district: 'Gazipur', area: 'Mollapara(Kashimpur)' },
    { district: 'Gazipur', area: 'Joyertek(Ambag Road-Konabari)' },
    { district: 'Gazipur', area: 'Dhaladia (Kapasia)' },
    { district: 'Gazipur', area: 'Rajabari -Sreepur Road(Gazipur)' },
    { district: 'Gazipur', area: 'Gorgoria masterbari (Sreepur)' },
    { district: 'Gazipur', area: 'Barmi Sreepur (Sreepur )' },
    { district: 'Gazipur', area: 'Joina Bazar (Sreepur)' },
    { district: 'Gazipur', area: 'Kapasia Bazar (Kapasia)' },
    { district: 'Gazipur', area: 'Kapasia Tok Noyon (Kapasia)' },
    { district: 'Gazipur', area: 'Kapasia Amraid (Kapasia)' },
    { district: 'Gazipur', area: 'Rajendrapur Cantonment (Rajendrapur)' },
    { district: 'Gazipur', area: 'Kashimpur Bus Stop (Gazipur)' },
    { district: 'Gazipur', area: 'Jiter mor -Kashimpur (Gazipur)' },
    { district: 'Gazipur', area: 'Molla market-(Kashimpur)' },
    { district: 'Gazipur', area: 'Panishel(Kashimpur)' },
    { district: 'Gazipur', area: 'Sultan Market(Kashimpur)' },
    { district: 'Gazipur', area: 'Kazi Market(Kashimpur)' },
    { district: 'Gazipur', area: 'Bagbari (Kashimpur)' },
    { district: 'Gazipur', area: 'Berenda(Kashimpur)' },
    { district: 'Gazipur', area: 'Sorabo(Kashimpur)' },
    { district: 'Gazipur', area: 'Kashimpur Square(Gazipur)' },
    { district: 'Gazipur', area: 'Konabari Bus stand(Gazipur)' },
    { district: 'Gazipur', area: 'Konabari Jail khana(Gazipur)' },
    { district: 'Gazipur', area: 'Konabari Kuddus Nagar(Gazipur)' },
    { district: 'Gazipur', area: 'Konabari collage Gate(Gazipur)' },
    { district: 'Gazipur', area: 'Baimail -Konabari (Gazipur)' },
    { district: 'Gazipur', area: 'Pollibiddut-Konabari(Gazipur)' },
    { district: 'Gazipur', area: 'Mouchak Bazar(Kaliakair)' },
    { district: 'Gazipur', area: 'Shofipur Bus Stand (Kaliakair)' },
    { district: 'Gazipur', area: 'Bhawal Government College (Gazipur)' },
    { district: 'Gazipur', area: 'Itahata (Chandona Chowrasta)' },
    { district: 'Gazipur', area: 'Telipara(Chandona Chowrasta)' },
    { district: 'Gazipur', area: 'Great Wall Jame Masjid (Chandona Chowrasta)' },
    { district: 'Gazipur', area: 'Paler Math (Gazipur Chowrasta)' },
    { district: 'Gazipur', area: 'Police Line (Gazipur Chowrasta)' },
    { district: 'Gazipur', area: 'Borsha Hall (Gazipur Chowrasta)' },
    { district: 'Gazipur', area: 'kenakata Goli (Gazipur Chowrasta)' },
    { district: 'Gazipur', area: 'Dhigir Chala (Gazipur Chowrasta)' },
    { district: 'Gazipur', area: 'Najor (Gazipur Chowrasta)' },
    { district: 'Gazipur', area: 'Kodda bridge (Gazipur Chowrasta)' },
    { district: 'Gazipur', area: 'Bason Thana (Gazipur)' },
    { district: 'Gazipur', area: 'Polagach Road (Board Bazar)' },
    { district: 'Gazipur', area: 'Jajhor (Board Bazar)' },
    { district: 'Gazipur', area: 'Gacha Thana (Board Bazar)' },
    { district: 'Gazipur', area: 'Mukter Bari Road (Board Bazar)' },
    { district: 'Gazipur', area: 'Boro Mosjid Road (Board Bazar)' },
    { district: 'Gazipur', area: 'IUT Road (Board Bazar)' },
    { district: 'Gazipur', area: 'Colombiya (Gazipur By Pass Road)' },
    { district: 'Gazipur', area: 'Mogor Khal (Gazipur By Pass Road)' },
    { district: 'Gazipur', area: 'Navanar Mor (Gazipur By Pass Road)' },
    { district: 'Gazipur', area: 'Hoque Market (Gazipur By Pass Road)' },
    { district: 'Gazipur', area: 'Sattola Garments (Maleker Bari)' },
    { district: 'Gazipur', area: 'Bolakar Mor (Maleker Bari)' },
    { district: 'Gazipur', area: 'Jogitota ( Joydebpur)' },
    { district: 'Gazipur', area: 'College gate (Pubail)' },
    { district: 'Gazipur', area: 'Badhon (Pubail)' },
    { district: 'Gazipur', area: 'Bosuga (Pubail)' },
    { district: 'Gazipur', area: 'Bokhtarour ( kaliganj)' },
    { district: 'Gazipur', area: 'Fuldi ( kaliganj)' },
    { district: 'Gazipur', area: 'Dalan bazar ( kaliganj)' },
    { district: 'Gazipur', area: 'Awora khali ( kaliganj)' },
    { district: 'Gazipur', area: 'Sawraid ( kaliganj)' },
    { district: 'Gazipur', area: 'Chowrasta (Tongi)' },
    { district: 'Keraniganj', area: 'Chunkutia (Keraniganj)' },
    { district: 'Keraniganj', area: 'Am Bagicha (Keraniganj)' },
    { district: 'Keraniganj', area: 'Zia Nagor (Keraniganj)' },
    { district: 'Keraniganj', area: 'Imambari (Keraniganj)' },
    { district: 'Keraniganj', area: 'Kodomtoli (Keraniganj)' },
    { district: 'Keraniganj', area: 'Bondok Para (Keraniganj)' },
    { district: 'Keraniganj', area: 'Golam Bazar (Keraniganj)' },
    { district: 'Keraniganj', area: 'Par Gendaria (Keraniganj)' },
    { district: 'Keraniganj', area: 'Ekuria (Keraniganj)' },
    { district: 'Keraniganj', area: 'Kholamora (Keraniganj)' },
    { district: 'Keraniganj', area: 'Atibazar (Keraniganj)' },
    { district: 'Keraniganj', area: 'Abdullahpur (Keraniganj)' },
    { district: 'Savar', area: 'Tetuljhora, Hemayetpur, Savar' },
    { district: 'Savar', area: 'Hemayetpur Bazar, Savar' },
    { district: 'Savar', area: 'Bongaon Union, Savar' },
    { district: 'Savar', area: 'Ashulia Thana, Baipayl, Savar' },
    { district: 'Savar', area: 'Charigram, Savar' },
    { district: 'Savar', area: 'Polli Biddut, Nabinagar, Savar' },
    { district: 'Savar', area: 'Norosinhopur, Ashulia, Savar' },
    { district: 'Savar', area: 'Zirabo Bazar, Ashulia, Savar' },
    { district: 'Savar', area: 'Savar City Center' },
    { district: 'Savar', area: 'Rajasion, Polo Market' },
    { district: 'Savar', area: 'Kathgora Bazar, Savar' },
    { district: 'Savar', area: 'Jamgora, Ashulia, Savar' },
    { district: 'Savar', area: 'Baipayl Kacha Bazar, Ashulia, Savar' },
    { district: 'Savar', area: 'Jahangirnagar University, Savar' },
    { district: 'Savar', area: 'Akran Bazar, Ashulia, Savar' },
    { district: 'Savar', area: 'Birulia Bridge, Savar' },
    { district: 'Savar', area: 'Nama Bazar, Savar' },
    { district: 'Savar', area: 'Jhawchar Bazar, Hemayetpur, Savar' },
    { district: 'Savar', area: 'Amin Bazar, Savar' },
    { district: 'Savar', area: 'Bhakurta Bazar, Amin Bazar, Savar' },
    { district: 'Savar', area: 'Mograkanda, Amin Bazar, Savar' },
    { district: 'Savar', area: 'Shamlasi Gudaraghat, Amin Bazar, Savar' },
    { district: 'Dhamrai', area: 'Niribili Dhamrai' },
    { district: 'Dhamrai', area: 'Golam Hafiz College Dhamrai' },
    { district: 'Dhamrai', area: 'Noyarhat Dhamrai' },
    { district: 'Dhamrai', area: 'Dhulivita (Dhamrai)' },
    { district: 'Dhamrai', area: 'Kalampur (Dhamrai)' },
    { district: 'Dhamrai', area: 'Bathuli Bustand (Dhamrai)' },
    { district: 'Dhamrai', area: 'Kushura Bustand (Dhamrai' },
    { district: 'Dhamrai', area: 'Baro Baria (Dhamrai)' },
    { district: 'Dhamrai', area: 'Dhantara Bazar (Dhamrai)' },
    { district: 'Dhamrai', area: 'Dhamrai Bazar' },
    { district: 'Dhamrai', area: 'Gurapir Mazar Dhamrai' },
    { district: 'Dhamrai', area: 'Beltola Dhamrai' },
    { district: 'Dhamrai', area: 'Dendabor Dhamrai' },
    { district: 'Dhamrai', area: 'Anayetpur Dhamrai' },
    { district: 'Dhamrai', area: 'Gonoshasthaya Dhamrai' },
    { district: 'Dhamrai', area: 'Dhamshona Bazar Dhamrai' },
    { district: 'Dhamrai', area: 'Kamalget Dhamrai' },
    { district: 'Dhamrai', area: 'Namabazar Dhamrai' },
    { district: 'Dhamrai', area: 'Khaicha Bari Dhamrai' },
    { district: 'Dhamrai', area: 'Konda Dhamrai' },
    { district: 'Dhamrai', area: 'Baipail Dhamrai' },
    { district: 'Dhamrai', area: 'Sreepur Dhamrai' },
    { district: 'Dhamrai', area: 'Mojarmil Dhamrai' },
    { district: 'Dhamrai', area: 'Khorar Chor (Dhamrai)' },
    { district: 'Dhamrai', area: 'Fudnagar Rupnagar (Dhamrai)' },
    { district: 'Dhamrai', area: 'Councill Bazar (Dhamrai)' },
    { district: 'Dhamrai', area: 'Kawalipara (Dhamrai)' },
    { district: 'Dhamrai', area: 'Chokroborti Dhamrai' },
    { district: 'Dhamrai', area: 'Beximco Dhamrai' },
    { district: 'Dhamrai', area: 'Bhadail DEPZ Dhamrai' },
    { district: 'Kaliakoir', area: 'Nobi Textile Kaliakoir' },
    { district: 'Kaliakoir', area: 'Zirani Kaliakoir' },
    { district: 'Kaliakoir', area: 'Kobirpur Kaliakoir' },
    { district: 'Kaliakoir', area: 'Baroipara Kaliakoir' },
    { district: 'Kaliakoir', area: 'Nondon Park Kaliakoir' },
    { district: 'Kaliakoir', area: 'Mannan Collage Road (Kaliakoir)' },
    { district: 'Kaliakoir', area: 'Turag Germent (Kaliakoir)' },
    { district: 'Kaliakoir', area: 'Mashi Hata (Kaliakoir)' },
    { district: 'Kaliakoir', area: 'Enargy Pack Germent (Kaliakoir)' },
    { district: 'Kaliakoir', area: 'Bengol (Kaliakoir)' },
    { district: 'Kaliakoir', area: 'Polash Housing (Kaliakoir)' },
    { district: 'Narayanganj', area: 'Modonpur Sadar (Modonpur)' },
    { district: 'Narayanganj', area: 'Kachpur (Modonpur Narayanganj)' },
    { district: 'Narayanganj', area: 'Nabiganj (Bandar Narayanganj)' },
    { district: 'Narayanganj', area: 'Modonganj (Bandar Naraynaganj)' },
    { district: 'Narayanganj', area: 'Morgapara (Sonargaon)' },
    { district: 'Narayanganj', area: 'Baiddar Bazar (Sonargaon)' },
];

const divisionData = [
  { "name": "Dhaka", "districts": ["Dhaka", "Faridpur", "Gazipur", "Gopalganj", "Kishoreganj", "Madaripur", "Manikganj", "Munshiganj", "Narayanganj", "Narsingdi", "Rajbari", "Shariatpur", "Tangail", "Tongi", "Savar", "Demra", "Keranigonj", "Dhamrai", "Kaliakoir", "Narsingdi"] },
  { "name": "Chattagram", "districts": ["Chattogram", "Bandarban", "Brahmanbaria", "Chandpur", "Cumilla", "Cox's Bazar", "Feni", "Khagrachhari", "Lakshmipur", "Noakhali", "Rangamati"] },
  { "name": "Rajshahi", "districts": ["Rajshahi", "Bogura", "Joypurhat", "Naogaon", "Natore", "Chapai Nawabganj", "Pabna", "Sirajganj"] },
  { "name": "Khulna", "districts": ["Khulna", "Bagerhat", "Chuadanga", "Jashore", "Jhenaidah", "Kushtia", "Magura", "Meherpur", "Narail", "Satkhira"] },
  { "name": "Barishal", "districts": ["Barishal", "Barguna", "Bhola", "Jhalokati", "Patuakhali", "Pirojpur"] },
  { "name": "Sylhet", "districts": ["Sylhet", "Habiganj", "Moulvibazar", "Sunamganj"] },
  { "name": "Rangpur", "districts": ["Rangpur", "Dinajpur", "Gaibandha", "Kurigram", "Lalmonirhat", "Nilphamari", "Panchagarh", "Thakurgaon"] },
  { "name": "Mymensingh", "districts": ["Mymensingh", "Jamalpur", "Netrokona", "Sherpur"] }
]

export const divisions = divisionData;

export const getDistrictsByDivision = (divisionName: string) => {
    const division = divisions.find(d => d.name === divisionName);
    return division ? division.districts : [];
}

export const getAreasByDistrict = (divisionName: string, districtName: string) => {
    return [...new Set(deliveryData
        .filter(d => d.district === districtName)
        .map(d => d.area))];
}
