
export const bangladeshGeoData = {
  "Dhaka": {
    "Dhaka": {
      "Mohammadpur": [
        "Salimullah Road(Mohammadpur)",
        "Adabor(Mohammadpur)",
        "Rayer Bazar(Mohammadpur)",
        "Dhaka Uddyan(Mohammadpur)",
        "Shekhertek(Mohammadpur)",
        "Dhaka uddan(Mohammadpur)",
        "Nobodoy(Mohammadpur)",
        "Chad Uddan(Mohammadpur)",
        "Mohammadia Housing(Mohammadpur)",
        "Tajmahal Road(Mohammadpur)",
        "Nurjahan Road(Mohammadpur)",
        "Rajia Sultana Road(Mohammadpur)",
        "Kaderabad Housing(Mohammadpur)",
        "Eastern Housing (Mohammadpur)",
        "Sadek Khan Road(Mohammadpur)",
        "Sher e Bangla Road(Mohammadpur)",
        "Katasur(Mohammadpur)",
        "Garden City(Mohammadpur)",
        "Boddhovumi(Mohammadpur)",
        "Modhu Bazar(Mohammadpur)",
        "Baroikhali (Mohammadpur)"
      ],
      "Dhanmondi": [
        "Dhanmondi - Road 3",
        "Sukrabad(Dhanmondi)",
        "Jigatola(Dhanmondi)",
        "Tallabag(Dhanmondi)",
        "Sobhanbag(Dhanmondi)",
        "Jhigatola(Dhanmondi)",
        "Shukrabad(Dhanmondi)",
        "Dhanmondi - Rd 1",
        "Dhanmondi - Rd 2",
        "Dhanmondi - Road 4",
        "Dhanmondi - Road 4A",
        "Dhanmondi - Rd 6",
        "Dhanmondi - Rd 3A",
        "Dhanmondi - Rd 6A",
        "Dhanmondi - Rd 8",
        "Dhanmondi - Rd 8A",
        "Dhanmondi - Rd 9",
        "Dhanmondi - Road 9/A",
        "Dhanmondi - Rd 10",
        "Dhanmondi - Rd 12",
        "Dhanmondi - Rd 12A",
        "Dhanmondi - Rd 15",
        "Dhanmondi - Rd 15 A",
        "Dhanmondi - Rd 27",
        "Dhanmondi - Rd 28",
        "Dhanmondi - Rd 29",
        "Jigatala post office(Dhanmondi)"
      ],
      "General": [
        "Gulshan-1 Road-1",
        "Sher-e-Bangla Agricultural University",
        "Baridhara Diplomatic Zone",
        "Baridhara DOHS",
        "Uttor Badda",
        "Middle Badda",
        "South Badda",
        "Merul Badda",
        "Banani Block A",
        "Banani DOHS",
        "Mohakhali DOHS",
        "Dhaka University",
        "Dhaka Medical College",
        "Sadarghat Dhaka",
        "CWH",
        "Nadda",
        "Poschim Badda",
        "Purbo Badda",
        "North Badda",
        "Tongi College Gate",
        "Mazar Road Uttarkhan",
        "Ainusbag-Dakshinkhan",
        "SDA",
        "Dhanmondi Staff Quarter",
        "Banani Block B",
        "Banani Block C",
        "Banani Block D",
        "Banani Block E",
        "Banani Block F",
        "Banani Block G",
        "Banani Block H",
        "Banani Block I",
        "Banani Block J",
        "Banani Block K",
        "Banani Block L",
        "Baridhara J block",
        "Baridhara K block",
        "Gulshan-1 Road-3",
        "Gulshan-1 Road-4",
        "Gulshan-1 Road-5",
        "Gulshan-1 Road-6",
        "Gulshan-1 Road-7",
        "Gulshan-1 Road-8",
        "Gulshan-1 Road-9",
        "Gulshan-1 Road-10",
        "Gulshan-1 Road-11",
        "Gulshan-1 Road-12",
        "Gulshan-1 Road-13",
        "Gulshan-1 Road-14",
        "Gulshan-1 Road-15",
        "Gulshan-1 Road-16",
        "Gulshan-1 Road-17",
        "Gulshan-1 Road-18",
        "Gulshan-1 Road-19",
        "Gulshan-1 Road-20",
        "Gulshan-1 Road-21",
        "Gulshan-1 Road-22",
        "Gulshan-1 Road-23",
        "Gulshan-1 Road-24",
        "Gulshan-1 Road-25",
        "Gulshan-1 Road-26",
        "Gulshan-1 Road-27",
        "Gulshan-1 Road-28",
        "Gulshan-1 Road-29",
        "Gulshan-1 Road-30",
        "Gulshan-1 Road-31",
        "Gulshan-1 Road-32",
        "Gulshan-1 Road-123",
        "Gulshan-1 Road-124",
        "Gulshan-1 Road-125",
        "Gulshan-1 Road-126",
        "Gulshan-1 Road-127",
        "Gulshan-1 Road-128",
        "Gulshan-1 Road-129",
        "Gulshan-1 Road-130",
        "Gulshan-1 Road-131",
        "Gulshan-1 Road-132",
        "Gulshan-1 Road-133",
        "Gulshan-1 Road-134",
        "Gulshan-1 Road-135",
        "Gulshan-1 Road-136",
        "Gulshan-1 Road-137",
        "Gulshan-1 Road-138",
        "Gulshan-1 Road-139",
        "Gulshan-1 Road-140",
        "Gulshan-1 Road-141",
        "Gulshan-1 Road-143",
        "Gulshan-1 Road-144",
        "Gulshan-1 Road-142",
        "Gulshan-2 Road-33",
        "Gulshan-2 Road-34",
        "Gulshan-2 Road-35",
        "Gulshan-2 Road-36",
        "Gulshan-2 Road-37",
        "Gulshan-2 Road-38",
        "Gulshan-2 Road-39",
        "Gulshan-2 Road-40",
        "Gulshan-2 Road-41",
        "Gulshan-2 Road-42",
        "Gulshan-2 Road-43",
        "Gulshan-2 Road-44",
        "Gulshan-2 Road-45",
        "Gulshan-2 Road-46",
        "Gulshan-2 Road-47",
        "Gulshan-2 Road-48",
        "Gulshan-2 Road-49",
        "Gulshan-2 Road-50",
        "Gulshan-2 Road-51",
        "Gulshan-2 Road-52",
        "Gulshan-2 Road-53",
        "Gulshan-2 Road-54",
        "Gulshan-2 Road-55",
        "Gulshan-2 Road-56",
        "Gulshan-2 Road-57",
        "Gulshan-2 Road-58",
        "Gulshan-2 Road-59",
        "Gulshan-2 Road-60",
        "Gulshan-2 Road-61",
        "Gulshan-2 Road-62",
        "Gulshan-2 Road-63",
        "Gulshan-2 Road-64",
        "Gulshan-2 Road-65",
        "Gulshan-2 Road-66",
        "Gulshan-2 Road-67",
        "Gulshan-2 Road-68",
        "Gulshan-2 Road-69",
        "Gulshan-2 Road-70",
        "Gulshan-2 Road-71",
        "Gulshan-2 Road-72",
        "Gulshan-2 Road-73",
        "Gulshan-2 Road-74",
        "Gulshan-2 Road-75",
        "Gulshan-2 Road-76",
        "Gulshan-2 Road-77",
        "Gulshan-2 Road-78",
        "Gulshan-2 Road-79",
        "Gulshan-2 Road-80",
        "Gulshan-2 Road-81",
        "Gulshan-2 Road-82",
        "Gulshan-2 Road-83",
        "Gulshan-2 Road-84",
        "Gulshan-2 Road-85",
        "Gulshan-2 Road-86",
        "Gulshan-2 Road-87",
        "Gulshan-2 Road-88",
        "Gulshan-2 Road-89",
        "Gulshan-2 Road-90",
        "Gulshan-2 Road-91",
        "Gulshan-2 Road-92",
        "Gulshan-2 Road-93",
        "Gulshan-2 Road-94",
        "Gulshan-2 Road-95",
        "Gulshan-2 Road-96",
        "Gulshan-2 Road-97",
        "Gulshan-2 Road-98",
        "Gulshan-2 Road-99",
        "Gulshan-2 Road-100",
        "Gulshan-2 Road-101",
        "Gulshan-2 Road-102",
        "Gulshan-2 Road-103",
        "Gulshan-2 Road-104",
        "Gulshan-2 Road-105",
        "Gulshan-2 Road-106",
        "Gulshan-2 Road-107",
        "Gulshan-2 Road-108",
        "Gulshan-2 Road-109",
        "Gulshan-2 Road-110",
        "Gulshan-2 Road-111",
        "Gulshan-2 Road-112",
        "Gulshan-2 Road-113",
        "Gulshan-2 Road-114",
        "Gulshan-2 Road-115",
        "Gulshan-2 Road-116",
        "Gulshan-2 Road-117",
        "Gulshan-2 Road-118",
        "Gulshan-2 Road-119",
        "Gulshan-2 Road-120",
        "Gulshan-2 Road-121",
        "Gulshan-2 Road-122",
        "Kurmitoal General Hospital",
        "Dhaka Cantonment post office",
        "Shaheed Ramiz Uddin Gate- MES",
        "Shaheed Ramiz Uddin Cantonment College",
        "Armed Forces Medical institute-MES",
        "Staff road officers querters-MES",
        "Sopnopuri Bashundhara R/A",
        "Mugda Medical College)Dhaka)",
        "Savar",
        "Nabinagar",
        "Ashulia",
        "Baipayl",
        "Dhamrai",
        "Nolam Dhamrai",
        "EPZ",
        "Tongi Bus Stand",
        "Tetuljhora",
        "Hemayetpur Bazar",
        "Bongaon Union",
        "Ashulia Thana",
        "Charigram",
        "Polli Biddut",
        "Norosinhopur",
        "Zirabo Bazar",
        "Savar City Center",
        "Rajasion",
        "Kathgora Bazar",
        "Jamgora",
        "Baipayl Kacha Bazar",
        "Jahangirnagar University",
        "Akran Bazar",
        "Birulia Bridge",
        "Nama Bazar",
        "Jhawchar Bazar",
        "Amin Bazar",
        "Bhakurta Bazar",
        "Mograkanda",
        "Shamlasi Gudaraghat",
        "Niribili Dhamrai",
        "Golam Hafiz College Dhamrai",
        "Noyarhat Dhamrai",
        "Kushura Bustand (Dhamrai",
        "Dhamrai Bazar",
        "Gurapir Mazar Dhamrai",
        "Beltola Dhamrai",
        "Dendabor Dhamrai",
        "Anayetpur Dhamrai",
        "Gonoshasthaya Dhamrai",
        "Dhamshona Bazar Dhamrai",
        "Kamalget Dhamrai",
        "Namabazar Dhamrai",
        "Khaicha Bari Dhamrai",
        "Konda Dhamrai",
        "Baipail Dhamrai",
        "Sreepur Dhamrai",
        "Mojarmil Dhamrai",
        "Chokroborti Dhamrai",
        "Beximco Dhamrai",
        "Bhadail DEPZ Dhamrai",
        "Nobi Textile Kaliakoir",
        "Zirani Kaliakoir",
        "Kobirpur Kaliakoir",
        "Baroipara Kaliakoir",
        "Nondon Park Kaliakoir",
        "Rampura TSO"
      ],
    }
  }
};

export const divisions = Object.keys(bangladeshGeoData);

export const getDistrictsByDivision = (division: string): string[] => {
  if (!division || !bangladeshGeoData[division as keyof typeof bangladeshGeoData]) {
    return [];
  }
  const divisionData = bangladeshGeoData[division as keyof typeof bangladeshGeoData];
  return Array.from(new Set(Object.keys(divisionData)));
};

export const getUpazilasByDistrict = (division: string, district: string): string[] => {
    if (!division || !district || !bangladeshGeoData[division as keyof typeof bangladeshGeoData]) {
        return [];
    }
    const divisionData = bangladeshGeoData[division as keyof typeof bangladeshGeoData];
    // @ts-ignore
    const districtData = divisionData[district];

    if(!districtData) return [];

    return Object.keys(districtData);
};

export const getUnionsByUpazila = (division: string, district: string, upazila: string): string[] => {
    if (!division || !district || !upazila || !bangladeshGeoData[division as keyof typeof bangladeshGeoData]) {
        return [];
    }
    // @ts-ignore
    const divisionData = bangladeshGeoData[division];
    if (!divisionData) return [];

    const districtData = divisionData[district];
    if (!districtData) return [];

    const upazilaData = districtData[upazila];
    if (!upazilaData || !Array.isArray(upazilaData)) return [];
    
    // Assuming upazilaData is an array of objects with an 'area' property
    return upazilaData.map((item: { area: string }) => item.area);
};
